#!/usr/bin/env bash
# Installing nginx

apt-get update
apt-get install -y nginx
sudo service nginx start
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
