#!/usr/bin/env bash
# Script to display "Holberton School" 10 times

num=1

while [ $num -le 10 ]; do
      echo "Holberton School"
      if [ $num -eq 9 ]; then
      	 echo "Hi"
	 fi
	 num=$((num + 1))
done
