#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

num=1

while [ $num -le 10 ]; do
      if [ $num -eq 4 ]; then
      	 echo "bad luck"
	 elif [ $num -eq 8 ]; then
	      echo "good luck"
	      else
		echo "Holberton School"
		fi
		num=$((num + 1))
done
