#!/usr/bin/env bash
#Script to display "Holberton School" 10 times

hours=0
min=1

while [ $hours -le 12 ]; do
 echo "Hour: $hours"
 min=1
 while [ $min -le 59 ]; do
  echo $min
   min=$((min + 1))
   done
 hours=$((hours + 1))
done
