#!/usr/bin/env bash
#Configure Ubuntu server with 127.0.0.2 as localhost
#8.8.8.8 as facebook ip

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.new
echo '8.8.8.8 facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm -f ~/hosts.new
